version: "3.7"
services:

  # MySQL
  mysql:
    image: mysql:latest
    volumes:
      - ./data/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dove
      - MYSQL_ROOT_PASSWORD=123456

  # Consul
  consul:
    image: consul:latest
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600/udp"
