// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/dove-one/dove/server/cmd/api/config"
	"github.com/dove-one/dove/server/cmd/api/initialize"
	"github.com/dove-one/dove/server/cmd/api/initialize/rpc"
)

func main() {
	// initialize
	//initialize.InitLogger()
	initialize.InitConfig()
	r, info := initialize.InitRegistry()
	rpc.Init()

	h := server.New(
		server.WithALPN(true),
		server.WithHostPorts(fmt.Sprintf(":%d", config.GlobalServerConfig.Port)),
		server.WithRegistry(r, info),
		server.WithHandleMethodNotAllowed(true),
	)
	register(h)
	h.Spin()
}
