// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/dove-one/dove/server/cmd/api/biz/model/user"
	"github.com/dove-one/dove/server/cmd/api/config"
	userRpc "github.com/dove-one/dove/server/common/kitex_gen/user"
)

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	res, err := config.GlobalUserClient.Login(ctx, &userRpc.LoginRequest{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		return
	}

	//resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, res)
}
