// Code generated by Kitex v0.5.2. DO NOT EDIT.

package authservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	auth "github.com/dove-one/dove/server/common/kitex_gen/auth"
)

func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

var authServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*auth.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{
		"UserCheckAuth": kitex.NewMethodInfo(userCheckAuthHandler, newAuthServiceUserCheckAuthArgs, newAuthServiceUserCheckAuthResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "auth",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func userCheckAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceUserCheckAuthArgs)
	realResult := result.(*auth.AuthServiceUserCheckAuthResult)
	success, err := handler.(auth.AuthService).UserCheckAuth(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceUserCheckAuthArgs() interface{} {
	return auth.NewAuthServiceUserCheckAuthArgs()
}

func newAuthServiceUserCheckAuthResult() interface{} {
	return auth.NewAuthServiceUserCheckAuthResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserCheckAuth(ctx context.Context, req *auth.UserCheckAuthReq) (r *auth.UserCheckAuthResp, err error) {
	var _args auth.AuthServiceUserCheckAuthArgs
	_args.Req = req
	var _result auth.AuthServiceUserCheckAuthResult
	if err = p.c.Call(ctx, "UserCheckAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
